// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/proto/monitor/monitor.proto

package monitor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	LocalIp       string                 `protobuf:"bytes,3,opt,name=local_ip,json=localIp,proto3" json:"local_ip,omitempty"`
	GrpcPort      int32                  `protobuf:"varint,4,opt,name=grpc_port,json=grpcPort,proto3" json:"grpc_port,omitempty"`
	Meta          map[string]string      `protobuf:"bytes,5,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_proto_monitor_monitor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_monitor_monitor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_monitor_monitor_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetLocalIp() string {
	if x != nil {
		return x.LocalIp
	}
	return ""
}

func (x *RegisterRequest) GetGrpcPort() int32 {
	if x != nil {
		return x.GrpcPort
	}
	return 0
}

func (x *RegisterRequest) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_api_proto_monitor_monitor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_monitor_monitor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_monitor_monitor_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeregisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterRequest) Reset() {
	*x = DeregisterRequest{}
	mi := &file_api_proto_monitor_monitor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterRequest) ProtoMessage() {}

func (x *DeregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_monitor_monitor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterRequest.ProtoReflect.Descriptor instead.
func (*DeregisterRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_monitor_monitor_proto_rawDescGZIP(), []int{2}
}

func (x *DeregisterRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type DeregisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterResponse) Reset() {
	*x = DeregisterResponse{}
	mi := &file_api_proto_monitor_monitor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterResponse) ProtoMessage() {}

func (x *DeregisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_monitor_monitor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterResponse.ProtoReflect.Descriptor instead.
func (*DeregisterResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_monitor_monitor_proto_rawDescGZIP(), []int{3}
}

func (x *DeregisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_api_proto_monitor_monitor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_monitor_monitor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_monitor_monitor_proto_rawDescGZIP(), []int{4}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_api_proto_monitor_monitor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_monitor_monitor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_monitor_monitor_proto_rawDescGZIP(), []int{5}
}

func (x *PingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// === NUEVO: GetMetrics ===
type GetMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsRequest) Reset() {
	*x = GetMetricsRequest{}
	mi := &file_api_proto_monitor_monitor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsRequest) ProtoMessage() {}

func (x *GetMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_monitor_monitor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetMetricsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_monitor_monitor_proto_rawDescGZIP(), []int{6}
}

type GetMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	CpuLoad       float32                `protobuf:"fixed32,2,opt,name=cpu_load,json=cpuLoad,proto3" json:"cpu_load,omitempty"` // Porcentaje 0.0-100.0
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsResponse) Reset() {
	*x = GetMetricsResponse{}
	mi := &file_api_proto_monitor_monitor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsResponse) ProtoMessage() {}

func (x *GetMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_monitor_monitor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetMetricsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_monitor_monitor_proto_rawDescGZIP(), []int{7}
}

func (x *GetMetricsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetMetricsResponse) GetCpuLoad() float32 {
	if x != nil {
		return x.CpuLoad
	}
	return 0
}

func (x *GetMetricsResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// === HU-15: Métricas Consolidadas ===
type AggregatedMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregatedMetricsRequest) Reset() {
	*x = AggregatedMetricsRequest{}
	mi := &file_api_proto_monitor_monitor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregatedMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregatedMetricsRequest) ProtoMessage() {}

func (x *AggregatedMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_monitor_monitor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregatedMetricsRequest.ProtoReflect.Descriptor instead.
func (*AggregatedMetricsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_monitor_monitor_proto_rawDescGZIP(), []int{8}
}

type AggregatedMetricsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	AvgCpuLoad        float32                `protobuf:"fixed32,2,opt,name=avg_cpu_load,json=avgCpuLoad,proto3" json:"avg_cpu_load,omitempty"`                   // Promedio de carga CPU
	TotalInstances    int32                  `protobuf:"varint,3,opt,name=total_instances,json=totalInstances,proto3" json:"total_instances,omitempty"`          // Total de instancias
	ActiveInstances   int32                  `protobuf:"varint,4,opt,name=active_instances,json=activeInstances,proto3" json:"active_instances,omitempty"`       // Instancias activas
	InactiveInstances int32                  `protobuf:"varint,5,opt,name=inactive_instances,json=inactiveInstances,proto3" json:"inactive_instances,omitempty"` // Instancias inactivas
	Instances         []*InstanceInfo        `protobuf:"bytes,6,rep,name=instances,proto3" json:"instances,omitempty"`                                           // Lista de instancias con sus métricas
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AggregatedMetricsResponse) Reset() {
	*x = AggregatedMetricsResponse{}
	mi := &file_api_proto_monitor_monitor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregatedMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregatedMetricsResponse) ProtoMessage() {}

func (x *AggregatedMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_monitor_monitor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregatedMetricsResponse.ProtoReflect.Descriptor instead.
func (*AggregatedMetricsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_monitor_monitor_proto_rawDescGZIP(), []int{9}
}

func (x *AggregatedMetricsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AggregatedMetricsResponse) GetAvgCpuLoad() float32 {
	if x != nil {
		return x.AvgCpuLoad
	}
	return 0
}

func (x *AggregatedMetricsResponse) GetTotalInstances() int32 {
	if x != nil {
		return x.TotalInstances
	}
	return 0
}

func (x *AggregatedMetricsResponse) GetActiveInstances() int32 {
	if x != nil {
		return x.ActiveInstances
	}
	return 0
}

func (x *AggregatedMetricsResponse) GetInactiveInstances() int32 {
	if x != nil {
		return x.InactiveInstances
	}
	return 0
}

func (x *AggregatedMetricsResponse) GetInstances() []*InstanceInfo {
	if x != nil {
		return x.Instances
	}
	return nil
}

type InstanceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Ip            string                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	CpuLoad       float32                `protobuf:"fixed32,4,opt,name=cpu_load,json=cpuLoad,proto3" json:"cpu_load,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	LastSeen      int64                  `protobuf:"varint,6,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstanceInfo) Reset() {
	*x = InstanceInfo{}
	mi := &file_api_proto_monitor_monitor_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceInfo) ProtoMessage() {}

func (x *InstanceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_monitor_monitor_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceInfo.ProtoReflect.Descriptor instead.
func (*InstanceInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_monitor_monitor_proto_rawDescGZIP(), []int{10}
}

func (x *InstanceInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InstanceInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *InstanceInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *InstanceInfo) GetCpuLoad() float32 {
	if x != nil {
		return x.CpuLoad
	}
	return 0
}

func (x *InstanceInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *InstanceInfo) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

type GetEventsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EventType      string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Severity       string                 `protobuf:"bytes,2,opt,name=severity,proto3" json:"severity,omitempty"`
	AfterTimestamp int64                  `protobuf:"varint,3,opt,name=after_timestamp,json=afterTimestamp,proto3" json:"after_timestamp,omitempty"`
	Limit          int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetEventsRequest) Reset() {
	*x = GetEventsRequest{}
	mi := &file_api_proto_monitor_monitor_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsRequest) ProtoMessage() {}

func (x *GetEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_monitor_monitor_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsRequest.ProtoReflect.Descriptor instead.
func (*GetEventsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_monitor_monitor_proto_rawDescGZIP(), []int{11}
}

func (x *GetEventsRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *GetEventsRequest) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *GetEventsRequest) GetAfterTimestamp() int64 {
	if x != nil {
		return x.AfterTimestamp
	}
	return 0
}

func (x *GetEventsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Events        []*SystemEvent         `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsResponse) Reset() {
	*x = GetEventsResponse{}
	mi := &file_api_proto_monitor_monitor_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsResponse) ProtoMessage() {}

func (x *GetEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_monitor_monitor_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsResponse.ProtoReflect.Descriptor instead.
func (*GetEventsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_monitor_monitor_proto_rawDescGZIP(), []int{12}
}

func (x *GetEventsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetEventsResponse) GetEvents() []*SystemEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type SystemEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Severity      string                 `protobuf:"bytes,3,opt,name=severity,proto3" json:"severity,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemEvent) Reset() {
	*x = SystemEvent{}
	mi := &file_api_proto_monitor_monitor_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemEvent) ProtoMessage() {}

func (x *SystemEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_monitor_monitor_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemEvent.ProtoReflect.Descriptor instead.
func (*SystemEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_monitor_monitor_proto_rawDescGZIP(), []int{13}
}

func (x *SystemEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SystemEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SystemEvent) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *SystemEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SystemEvent) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SystemEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_api_proto_monitor_monitor_proto protoreflect.FileDescriptor

const file_api_proto_monitor_monitor_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/proto/monitor/monitor.proto\x12\amonitor\"\xf7\x01\n" +
	"\x0fRegisterRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x19\n" +
	"\blocal_ip\x18\x03 \x01(\tR\alocalIp\x12\x1b\n" +
	"\tgrpc_port\x18\x04 \x01(\x05R\bgrpcPort\x126\n" +
	"\x04meta\x18\x05 \x03(\v2\".monitor.RegisterRequest.MetaEntryR\x04meta\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"F\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"4\n" +
	"\x11DeregisterRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\".\n" +
	"\x12DeregisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\r\n" +
	"\vPingRequest\"(\n" +
	"\fPingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x13\n" +
	"\x11GetMetricsRequest\"g\n" +
	"\x12GetMetricsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\bcpu_load\x18\x02 \x01(\x02R\acpuLoad\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"\x1a\n" +
	"\x18AggregatedMetricsRequest\"\x8f\x02\n" +
	"\x19AggregatedMetricsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12 \n" +
	"\favg_cpu_load\x18\x02 \x01(\x02R\n" +
	"avgCpuLoad\x12'\n" +
	"\x0ftotal_instances\x18\x03 \x01(\x05R\x0etotalInstances\x12)\n" +
	"\x10active_instances\x18\x04 \x01(\x05R\x0factiveInstances\x12-\n" +
	"\x12inactive_instances\x18\x05 \x01(\x05R\x11inactiveInstances\x123\n" +
	"\tinstances\x18\x06 \x03(\v2\x15.monitor.InstanceInfoR\tinstances\"\x9a\x01\n" +
	"\fInstanceInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\x12\x19\n" +
	"\bcpu_load\x18\x04 \x01(\x02R\acpuLoad\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1b\n" +
	"\tlast_seen\x18\x06 \x01(\x03R\blastSeen\"\x8c\x01\n" +
	"\x10GetEventsRequest\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x1a\n" +
	"\bseverity\x18\x02 \x01(\tR\bseverity\x12'\n" +
	"\x0fafter_timestamp\x18\x03 \x01(\x03R\x0eafterTimestamp\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"[\n" +
	"\x11GetEventsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12,\n" +
	"\x06events\x18\x02 \x03(\v2\x14.monitor.SystemEventR\x06events\"\x82\x02\n" +
	"\vSystemEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\bseverity\x18\x03 \x01(\tR\bseverity\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12>\n" +
	"\bmetadata\x18\x05 \x03(\v2\".monitor.SystemEvent.MetadataEntryR\bmetadata\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xc4\x02\n" +
	"\x0fMonitorSService\x12A\n" +
	"\bRegister\x12\x18.monitor.RegisterRequest\x1a\x19.monitor.RegisterResponse\"\x00\x12G\n" +
	"\n" +
	"Deregister\x12\x1a.monitor.DeregisterRequest\x1a\x1b.monitor.DeregisterResponse\"\x00\x12_\n" +
	"\x14GetAggregatedMetrics\x12!.monitor.AggregatedMetricsRequest\x1a\".monitor.AggregatedMetricsResponse\"\x00\x12D\n" +
	"\tGetEvents\x12\x19.monitor.GetEventsRequest\x1a\x1a.monitor.GetEventsResponse\"\x002\x91\x01\n" +
	"\x0fMonitorCService\x125\n" +
	"\x04Ping\x12\x14.monitor.PingRequest\x1a\x15.monitor.PingResponse\"\x00\x12G\n" +
	"\n" +
	"GetMetrics\x12\x1a.monitor.GetMetricsRequest\x1a\x1b.monitor.GetMetricsResponse\"\x00BCZAgithub.com/marendonq/distributed-ec2-autoscaler/api/proto/monitorb\x06proto3"

var (
	file_api_proto_monitor_monitor_proto_rawDescOnce sync.Once
	file_api_proto_monitor_monitor_proto_rawDescData []byte
)

func file_api_proto_monitor_monitor_proto_rawDescGZIP() []byte {
	file_api_proto_monitor_monitor_proto_rawDescOnce.Do(func() {
		file_api_proto_monitor_monitor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_monitor_monitor_proto_rawDesc), len(file_api_proto_monitor_monitor_proto_rawDesc)))
	})
	return file_api_proto_monitor_monitor_proto_rawDescData
}

var file_api_proto_monitor_monitor_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_api_proto_monitor_monitor_proto_goTypes = []any{
	(*RegisterRequest)(nil),           // 0: monitor.RegisterRequest
	(*RegisterResponse)(nil),          // 1: monitor.RegisterResponse
	(*DeregisterRequest)(nil),         // 2: monitor.DeregisterRequest
	(*DeregisterResponse)(nil),        // 3: monitor.DeregisterResponse
	(*PingRequest)(nil),               // 4: monitor.PingRequest
	(*PingResponse)(nil),              // 5: monitor.PingResponse
	(*GetMetricsRequest)(nil),         // 6: monitor.GetMetricsRequest
	(*GetMetricsResponse)(nil),        // 7: monitor.GetMetricsResponse
	(*AggregatedMetricsRequest)(nil),  // 8: monitor.AggregatedMetricsRequest
	(*AggregatedMetricsResponse)(nil), // 9: monitor.AggregatedMetricsResponse
	(*InstanceInfo)(nil),              // 10: monitor.InstanceInfo
	(*GetEventsRequest)(nil),          // 11: monitor.GetEventsRequest
	(*GetEventsResponse)(nil),         // 12: monitor.GetEventsResponse
	(*SystemEvent)(nil),               // 13: monitor.SystemEvent
	nil,                               // 14: monitor.RegisterRequest.MetaEntry
	nil,                               // 15: monitor.SystemEvent.MetadataEntry
}
var file_api_proto_monitor_monitor_proto_depIdxs = []int32{
	14, // 0: monitor.RegisterRequest.meta:type_name -> monitor.RegisterRequest.MetaEntry
	10, // 1: monitor.AggregatedMetricsResponse.instances:type_name -> monitor.InstanceInfo
	13, // 2: monitor.GetEventsResponse.events:type_name -> monitor.SystemEvent
	15, // 3: monitor.SystemEvent.metadata:type_name -> monitor.SystemEvent.MetadataEntry
	0,  // 4: monitor.MonitorSService.Register:input_type -> monitor.RegisterRequest
	2,  // 5: monitor.MonitorSService.Deregister:input_type -> monitor.DeregisterRequest
	8,  // 6: monitor.MonitorSService.GetAggregatedMetrics:input_type -> monitor.AggregatedMetricsRequest
	11, // 7: monitor.MonitorSService.GetEvents:input_type -> monitor.GetEventsRequest
	4,  // 8: monitor.MonitorCService.Ping:input_type -> monitor.PingRequest
	6,  // 9: monitor.MonitorCService.GetMetrics:input_type -> monitor.GetMetricsRequest
	1,  // 10: monitor.MonitorSService.Register:output_type -> monitor.RegisterResponse
	3,  // 11: monitor.MonitorSService.Deregister:output_type -> monitor.DeregisterResponse
	9,  // 12: monitor.MonitorSService.GetAggregatedMetrics:output_type -> monitor.AggregatedMetricsResponse
	12, // 13: monitor.MonitorSService.GetEvents:output_type -> monitor.GetEventsResponse
	5,  // 14: monitor.MonitorCService.Ping:output_type -> monitor.PingResponse
	7,  // 15: monitor.MonitorCService.GetMetrics:output_type -> monitor.GetMetricsResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_monitor_monitor_proto_init() }
func file_api_proto_monitor_monitor_proto_init() {
	if File_api_proto_monitor_monitor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_monitor_monitor_proto_rawDesc), len(file_api_proto_monitor_monitor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_proto_monitor_monitor_proto_goTypes,
		DependencyIndexes: file_api_proto_monitor_monitor_proto_depIdxs,
		MessageInfos:      file_api_proto_monitor_monitor_proto_msgTypes,
	}.Build()
	File_api_proto_monitor_monitor_proto = out.File
	file_api_proto_monitor_monitor_proto_goTypes = nil
	file_api_proto_monitor_monitor_proto_depIdxs = nil
}
