syntax = "proto3";

package monitor;

option go_package = "github.com/marendonq/distributed-ec2-autoscaler/api/proto/monitor";

// Servicios expuestos por el Servidor Central (MonitorS)
service MonitorSService {
  // HU-01: Registro y Desregistro
  rpc Register (RegisterRequest) returns (RegisterResponse) {}
  rpc Deregister (DeregisterRequest) returns (DeregisterResponse) {}
}

// Servicios expuestos por los Agentes (MonitorC)
service MonitorCService {
  // HU-02: Verificación de vivacidad (Ping)
  rpc Ping (PingRequest) returns (PingResponse) {}
  
  // GetMetrics: Obtener métricas de carga simulada del MonitorC
  rpc GetMetrics (GetMetricsRequest) returns (GetMetricsResponse) {}
  
  // Shutdown: Para apagado ordenado antes de que el ASG destruya la instancia
  rpc Shutdown (ShutdownRequest) returns (ShutdownResponse) {}
}

message RegisterRequest {
  string instance_id = 1;
  string hostname = 2;
  string local_ip = 3;
  int32 grpc_port = 4;
  map<string, string> meta = 5;
}

message RegisterResponse {
  bool success = 1;
  string message = 2;
}

message DeregisterRequest {
  string instance_id = 1;
}

message DeregisterResponse {
  bool success = 1;
}

message PingRequest {
}

message PingResponse {
  bool success = 1;
}

message GetMetricsRequest {
}

message GetMetricsResponse {
  float cpu_load = 1; // Carga simulada (onda sinusoidal)
  string instance_id = 2; // Para validación defensiva
}

message ShutdownRequest {
}

message ShutdownResponse {
  bool success = 1;
  string instance_id = 2;
}
