version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: teleproy2-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: teleuser
      POSTGRES_PASSWORD: telepass
      POSTGRES_DB: teledb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
